stages:
  - pre-deploy-tests
  - deploy
  - load-test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/

unit-tests:
  stage: pre-deploy-tests
  image: eclipse-temurin:17-jdk
  before_script:
    - apt-get update -qq && apt-get install -y -qq maven
  script:
    - mvn test -Dtest="!br.edu.iff.taskflowapi.integration.**"
  rules:
    - if: $CI_COMMIT_REF_NAME == "deploy_gitlab"

integration-tests:
  stage: pre-deploy-tests
  image: eclipse-temurin:17-jdk
  needs: ["unit-tests"]
  before_script:
    - apt-get update -qq && apt-get install -y -qq maven
  script:
    - mvn test -Dtest="br.edu.iff.taskflowapi.integration.**"
  rules:
    - if: $CI_COMMIT_REF_NAME == "deploy_gitlab"

security-test:
  stage: pre-deploy-tests
  image: eclipse-temurin:17-jdk
  needs: ["integration-tests"]
  before_script:
    - apt-get update -qq && apt-get install -y -qq maven curl
    - curl -o snyk https://static.snyk.io/cli/latest/snyk-linux
    - chmod +x snyk
    - mv snyk /usr/local/bin/
  script:
    - chmod +x ./mvnw
    - snyk auth $SNYK_TOKEN
    - snyk test --severity-threshold=high
  rules:
    - if: $CI_COMMIT_REF_NAME == "deploy_gitlab"

deploy-to-cloud-run:
  stage: deploy
  image: google/cloud-sdk:alpine
  needs: ["security-test"]
  rules:
    - if: $CI_COMMIT_REF_NAME == "deploy_gitlab"
  before_script:
    - echo $GCP_SA_KEY | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file gcp-key.json
    - gcloud config set project $GCP_PROJECT_ID
  script:
    - mkdir -p keys
    - echo "$RSA_PRIVATE_KEY" > keys/private_key.pem
    - echo "$RSA_PUBLIC_KEY" > keys/public_key.pem
    - gcloud run deploy taskflow-api
      --source .
      --region us-central1
      --allow-unauthenticated
      --memory=512Mi
      --cpu=1
      --set-env-vars SPRING_PROFILES_ACTIVE=prod

load-test:
  stage: load-test
  image: grafana/k6:latest
  needs: ["deploy-to-cloud-run"]
  script:
    - k6 run ./k6/load-test.js
  rules:
    - if: $CI_COMMIT_REF_NAME == "deploy_gitlab"